<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <ItemDefinitionGroup>
    <ClCompile>
	  <LanguageStandard>stdcpp17</LanguageStandard>
      <AdditionalIncludeDirectories>
		$(ProjectDir);
        $(ProjectDir)libs\imgui;
		$(ProjectDir)libs\imgui\backends;
        $(ProjectDir)libs\implot;
        %(AdditionalIncludeDirectories)
      </AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>

</Project>
